{{ if .Values.tcpRouter.enabled }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cf-tcp-router
  labels:
    app: cf-tcp-router
  annotations:
    checksum/cf-tcp-router-config: {{ include (print $.Template.BasePath "/cf-tcp-router-config.yaml") . | sha256sum }}
    checksum/haproxy-config: {{ include (print $.Template.BasePath "/haproxy-config.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cf-tcp-router
  template:
    metadata:
      labels:
        app: cf-tcp-router
      annotations:
        checksum/cf-tcp-router-config: {{ include (print $.Template.BasePath "/cf-tcp-router-config.yaml") . | sha256sum }}
        checksum/haproxy-config: {{ include (print $.Template.BasePath "/haproxy-config.yaml") . | sha256sum }}
    spec:
      shareProcessNamespace: true
      initContainers:
        - name: combine-certificates
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              set -e
              cat /certs/tls.crt /certs/tls.key > /tmp/tls-combined.pem
              cat /haproxy-original/haproxy.conf > /haproxy/haproxy.conf
          volumeMounts:
            - name: cf-tcp-router
              mountPath: /certs
            - name: tmp
              mountPath: /tmp
            - name: shared
              mountPath: /haproxy
            - name: haproxy-config
              mountPath: /haproxy-original/haproxy.conf
              subPath: haproxy.conf
      containers:
        - name: cf-tcp-router
          image: {{ .Values.tcpRouter.image.repository }}:{{ default .Chart.AppVersion .Values.tcpRouter.image.tag }}
          imagePullPolicy: {{ .Values.tcpRouter.image.imagePullPolicy }}
          args:
          - -logLevel=info
          - -timeFormat=rfc3339
          - -tcpLoadBalancerConfig=/haproxy/haproxy.conf
          - -tcpLoadBalancerBaseConfig=/haproxy-original/haproxy.conf
          - -tcpLoadBalancerStatsUnixSocket=/haproxy/haproxy.sock
          - -haproxyReloader=/usr/local/bin/haproxy_reloader.sh
          - -config=/cf-tcp-router/cf-tcp-router.yaml
          - -statsCollectionInterval=1m
          - -dropsondePort=3457
          - -routingGroupCheckExit=false
          {{- if .Values.tcpRouter.resources }}
          resources:
            {{- toYaml .Values.tcpRouter.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: cf-tcp-router
              mountPath: /etc/ssl/cf-tcp-router
            - name: cf-tcp-router-config
              mountPath: /cf-tcp-router
            - name: shared
              mountPath: /haproxy
            - name: haproxy-config
              mountPath: /haproxy-original/haproxy.conf
              subPath: haproxy.conf
            - name: tmp
              mountPath: /tmp
        - name: haproxy
          image: {{ .Values.tcpRouter.haproxy.image.repository }}:{{ .Values.tcpRouter.haproxy.image.tag }}
          imagePullPolicy: {{ .Values.tcpRouter.haproxy.image.imagePullPolicy }}
          args:
            - -W
            - -db
            - -p
            - /haproxy/haproxy.pid
            - -f
            - /haproxy/haproxy.conf
          {{- if .Values.tcpRouter.haproxy.resources }}
          resources:
            {{- toYaml .Values.tcpRouter.haproxy.resources | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: 80
          volumeMounts:
            - name: shared
              mountPath: /haproxy
            - name: cf-tcp-router
              mountPath: /etc/ssl/cf-tcp-router
            - name: tmp
              mountPath: /tmp
      {{- if .Values.tcpRouter.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.tcpRouter.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tcpRouter.tolerations }}
      tolerations:
        {{- toYaml .Values.tcpRouter.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: cf-tcp-router
          secret:
            secretName: {{ required "tcpRouter.certificateSecret is required" .Values.tcpRouter.certificateSecret }}
        - name: cf-tcp-router-config
          secret:
            secretName: cf-tcp-router-config
        - name: haproxy-config
          configMap:
            name: haproxy-config
        - name: shared
          emptyDir: {}
        - name: tmp
          emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: cf-tcp-router
  labels:
    app: cf-tcp-router
spec:
  selector:
    app: cf-tcp-router
  ports:
    - name: tcp-1
      port: 32000
      targetPort: 32000
    - name: tcp-2
      port: 32001
      targetPort: 32001
    - name: tcp-3
      port: 32002
      targetPort: 32002
    - name: tcp-4
      port: 32003
      targetPort: 32003
    - name: tcp-5
      port: 32004
      targetPort: 32004
    - name: tcp-6
      port: 32005
      targetPort: 32005
    - name: tcp-7
      port: 32006
      targetPort: 32006
    - name: tcp-8
      port: 32007
      targetPort: 32007
    - name: tcp-9
      port: 32008
      targetPort: 32008
    - name: tcp-10
      port: 32009
      targetPort: 32009
    - name: tcp-11
      port: 32010
      targetPort: 32010
    - name: tcp-12
      port: 32011
      targetPort: 32011
    - name: tcp-13
      port: 32012
      targetPort: 32012
    - name: tcp-14
      port: 32013
      targetPort: 32013
    - name: tcp-15
      port: 32014
      targetPort: 32014
    - name: tcp-16
      port: 32015
      targetPort: 32015
    - name: tcp-17
      port: 32016
      targetPort: 32016
    - name: tcp-18
      port: 32017
      targetPort: 32017
    - name: tcp-19
      port: 32018
      targetPort: 32018
    - name: tcp-20
      port: 32019
      targetPort: 32019
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-1
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-1
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32000
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-2
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-2
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32001
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-3
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-3
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32002
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-4
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-4
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32003
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-5
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-5
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32004
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-6
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-6
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32005
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-7
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-7
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32006
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-8
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-8
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32007
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-9
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-9
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32008
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-10
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-10
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32009
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-11
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-11
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32010
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-12
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-12
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32011
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-13
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-13
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32012
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-14
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-14
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32013
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-15
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-15
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32014
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-16
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-16
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32015
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-17
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-17
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32016
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-18
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-18
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32017
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-19
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-19
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32018
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-20
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-20
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: 32019
{{- end }}
