{{- if .Values.tcpRouter.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cf-tcp-router-configmap
data:
  cf-tcp-router.yaml: |-
    oauth:
      token_endpoint: {{ .Values.tcpRouter.uaa.address }}
      port: {{ .Values.tcpRouter.uaa.port }}
      client_name: "tcp_router"
      client_secret: {{ .Values.tcpRouter.oauthClientsSecret | quote }}
      skip_ssl_validation: false
      ca_certs: "/etc/ssl/cf-tcp-router/ca.crt"
    routing_api:
      uri: {{ .Values.tcpRouter.routingApi.address }}
      port: {{ .Values.tcpRouter.routingApi.port }}
      auth_disabled: false
      client_cert_path: "/etc/ssl/cf-tcp-router/tls.crt"
      ca_cert_path: "/etc/ssl/cf-tcp-router/ca.crt"
      client_private_key_path: "/etc/ssl/cf-tcp-router/tls.key"
    haproxy_pid_file: "/haproxy/haproxy.pid"
    isolation_segments: {{ .Values.tcpRouter.isolationSegments }}
    reserved_system_component_ports: []
    drain_wait: 20s
    backend_tls:
      enabled: true
      ca_cert_path: "/etc/ssl/cf-tcp-router/ca.crt"
      client_cert_and_key_path: "/tmp/tls-combined.pem"
    frontend_tls:
{{- end }}
