{{- if .Values.gorouter.enabled }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.gorouter.name }}
  labels:
    app: {{ .Values.gorouter.name }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/gorouter-configmap.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.gorouter.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.gorouter.name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/gorouter-configmap.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: gorouter-init
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - |
          set -e
          yq '
            .nats.ca_certs = strenv(CA_CRT) |
            .nats.cert_chain = strenv(TLS_CRT) |
            .nats.private_key = strenv(TLS_KEY) |
            .tls_pem[0].cert_chain = strenv(TLS_CRT) |
            .tls_pem[0].private_key = strenv(TLS_KEY) |
            .ca_certs[0] = strenv(CA_CRT) |
            .client_ca_certs = strenv(CA_CRT) |
            .backends.cert_chain = strenv(TLS_CRT) |
            .backends.private_key = strenv(TLS_KEY)' /gorouter/gorouter.yaml > /tmp/gorouter.yaml
        volumeMounts:
          - name: "{{ .Values.gorouter.name }}-config"
            mountPath: /gorouter
          - name: tmp
            mountPath: /tmp
        env:
          - name: CA_CRT
            valueFrom:
              secretKeyRef:
                name: {{ required "gorouter.certificateSecret is required" .Values.gorouter.certificateSecret }}
                key: ca.crt
          - name: TLS_CRT
            valueFrom:
              secretKeyRef:
                name: {{ required "gorouter.certificateSecret is required" .Values.gorouter.certificateSecret }}
                key: tls.crt
          - name: TLS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ required "gorouter.certificateSecret is required" .Values.gorouter.certificateSecret }}
                key: tls.key
      containers:
        - name: gorouter
          image: {{ .Values.gorouter.image.repository }}:{{ default .Chart.AppVersion .Values.gorouter.image.tag }}
          imagePullPolicy: {{ .Values.gorouter.image.imagePullPolicy }}
          args:
          - -c
          - /tmp/gorouter.yaml
          volumeMounts:
            - name: "{{ .Values.gorouter.name }}-config"
              mountPath: /gorouter
            - name: tmp
              mountPath: /tmp
          {{- if .Values.gorouter.resources }}
          resources:
            {{- toYaml .Values.gorouter.resources | nindent 12 }}
          {{- end }}
        - name: udp-forwarder
          image: {{ .Values.udpForwarder.image.repository }}:{{ .Values.udpForwarder.image.tag }}
          imagePullPolicy: {{ .Values.udpForwarder.image.imagePullPolicy }}
          {{- if .Values.udpForwarder.resources }}
          resources:
            {{- toYaml .Values.udpForwarder.resources | nindent 12 }}
          {{- end }}
          env:
            - name: UDP_PORT
              value: "3457"
            - name: LOGGREGATOR_AGENT_CA_FILE_PATH
              value: /etc/ssl/certs/udp-forwarder/ca.crt
            - name: LOGGREGATOR_AGENT_CERT_FILE_PATH
              value: /etc/ssl/certs/udp-forwarder/tls.crt
            - name: LOGGREGATOR_AGENT_KEY_FILE_PATH
              value: /etc/ssl/certs/udp-forwarder/tls.key
            - name: LOGGREGATOR_AGENT_ADDR
              value: "forwarder-agent.{{ .Release.Namespace }}.svc.cluster.local:3458"
            - name: METRICS_CA_FILE_PATH
              value: /etc/ssl/certs/udp-forwarder/ca.crt
            - name: METRICS_CERT_FILE_PATH
              value: /etc/ssl/certs/udp-forwarder/tls.crt
            - name: METRICS_KEY_FILE_PATH
              value: /etc/ssl/certs/udp-forwarder/tls.key
          volumeMounts:
            - name: udp-forwarder
              mountPath: /etc/ssl/certs/udp-forwarder
      {{- if .Values.gorouter.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.gorouter.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.gorouter.tolerations }}
      tolerations:
        {{- toYaml .Values.gorouter.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: "{{ .Values.gorouter.name }}-config"
          configMap:
            name: "{{ .Values.gorouter.name }}-configmap"
        - name: udp-forwarder
          secret:
            secretName: {{ required "udpForwarder.certificateSecret is required" .Values.udpForwarder.certificateSecret }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.gorouter.name }}
  labels:
    app: {{ .Values.gorouter.name }}
spec:
  ports:
  - port: 443
    name: https
    targetPort: 443
    appProtocol: kubernetes.io/h2c
  selector:
    app: {{ .Values.gorouter.name }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: {{ .Values.gorouter.name }}-tls
spec:
  targetRefs:
    - kind: Service
      group: ""
      name: {{ .Values.gorouter.name }}
  validation:
    hostname: "{{ .Values.gorouter.hostname }}"
    caCertificateRefs:
      - kind: ConfigMap
        group: ""
        name: ca
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.gorouter.name }}
  annotations:
    istio.io/preserve-host-header: "true"
spec:
  parentRefs:
    - name: istio-gateway
  hostnames:
    - "{{ .Values.gorouter.appsDomain }}"
  rules:
    - backendRefs:
        - name: {{ .Values.gorouter.name }}
          port: 443
{{- end }}