{{- if .Values.routingApi.enabled }}
{{ $_ := required ".Values.routingApi.sqldb.password must be provided" .Values.routingApi.sqldb.password }}
 kind: Secret
apiVersion: v1
metadata:
  name: routing-api-config
stringData:
  routing-api.yaml: |-
    ---
    log_guid: "routing_api"
    max_ttl: 120s
    system_domain: {{ .Values.routingApi.systemDomain | quote }}
    metron_config:
      address: forwarder-agent.{{ .Release.Namespace }}.svc.cluster.local
      port: 3458
    metrics_reporting_interval: 30s
    statsd_endpoint: localhost:8125
    oauth:
      token_endpoint: {{ tpl .Values.routingApi.uaa.address . }}
      port: {{ .Values.routingApi.uaa.port }}
      skip_ssl_validation: false
      ca_certs: "/etc/ssl/uaa/ca.crt"
    debug_address: "127.0.0.1:17002"
    statsd_client_flush_interval: 300ms
    router_groups:
    - name: default-tcp
      reservable_ports: 32000-32019
      type: tcp
    reserved_system_component_ports: []
    fail_on_router_port_conflicts: false
    uuid: 07c65e06-b676-4f4a-a37f-96df62d387d7
    admin_port: 15897
    api:
      listen_port: 3000
      http_enabled: true
      mtls_listen_port: 3001
      mtls_client_ca_file: "/etc/ssl/routing-api/ca.crt"
      mtls_server_cert_file: "/etc/ssl/routing-api/tls.crt"
      mtls_server_key_file: "/etc/ssl/routing-api/tls.key"
    sqldb:
      host: {{ tpl .Values.routingApi.sqldb.address . }}
      port: {{ .Values.routingApi.sqldb.port }}
      type: postgres
      schema: routing_api
      username: {{ .Values.routingApi.sqldb.user }}
      password: {{ .Values.routingApi.sqldb.password | quote }}
      skip_hostname_validation: {{ .Values.routingApi.sqldb.skipSSLVerify }}
      skip_ssl_validation: {{ .Values.routingApi.sqldb.skipSSLVerify }}
      {{- if not .Values.routingApi.sqldb.skipSSLVerify }}
      ca_cert: |-
        $DB_CA_CRT
      {{- end }}
      max_open_connections: 200
      max_idle_connections: 10
      connections_max_lifetime_seconds: 3600
    lock_ttl: 10s
    retry_interval: 5s
    locket:
      locket_address: {{ tpl .Values.routingApi.locketAddress . }}
      locket_ca_cert_file: "/etc/ssl/locket/ca.crt"
      locket_client_cert_file: "/etc/ssl/locket/tls.crt"
      locket_client_key_file: "/etc/ssl/locket/tls.key"
{{- end }}
