
{
    "admin_password": "${CC_ADMIN_PASSWORD}",
    "admin_user": "ccadmin",
    "api": "api.127-0-0-1.nip.io",
    "apps_domain": "apps.127-0-0-1.nip.io",
    "credhub_client": "credhub_admin_client",
    "credhub_location": "https://credhub.127-0-0-1.nip.io",
    "credhub_mode": "assisted",
    "credhub_secret": "${OAUTH_CLIENTS_SECRET}",
    "isolation_segment_name": "isolated",
    "private_docker_registry_image": "${CATS_PRIVATE_DOCKER_IMAGE}",
    "private_docker_registry_password": "${CATS_PRIVATE_DOCKER_PASSWORD}",
    "private_docker_registry_username": "${CATS_PRIVATE_DOCKER_USERNAME}",
    "public_docker_app_image": "cloudfoundry/diego-docker-app@sha256:6778850ceba30b871153da93c19a954a7c1ec8f02e6113e26612e35168c9a63b",
    "skip_ssl_validation": true,
    "timeout_scale": 2,
    "use_http": false,

    "include_app_syslog_tcp": false,
    "include_apps": false,
    "include_cnb": false,
    "include_container_networking": false,
    "include_deployments": false,
    "include_detect": false,
    "include_docker": false,
    "include_file_based_service_bindings": false,
    "include_http2_routing": false,
    "include_internet_dependent": false,
    "include_ipv6": false,
    "include_isolation_segments": false,
    "include_private_docker_registry": false,
    "include_route_services": false,
    "include_routing": false,
    "include_routing_isolation_segments": false,
    "include_security_groups": false,
    "include_service_discovery": false,
    "include_service_instance_sharing": false,
    "include_services": false,
    "include_ssh": false,
    "include_sso": false,
    "include_tasks": false,
    "include_tcp_routing": false,
    "include_user_provided_services": false,
    "include_tcp_isolation_segments": false,
    "include_v3": false,
    "include_volume_services": true,
    "include_windows": false,
    "include_zipkin": false,

    "volume_service_name": "nfs",
    "volume_service_plan_name": "Existing",
    "volume_service_create_config": "{\"share\": \"nfs-server/export/test-share\"}",


    "java_buildpack_name": "java-buildpack",
    "ruby_buildpack_name": "ruby_buildpack",
    "nodejs_buildpack_name": "nodejs_buildpack",
    "binary_buildpack_name": "binary_buildpack",
    "go_buildpack_name": "go_buildpack",
    "python_buildpack_name": "python_buildpack"
}