gorouter:
  enabled: true
  certificateSecret: "all-in-one-tls"
  name: gorouter-iso-seg
  hostname: "gorouter-iso-seg.127-0-0-1.nip.io"
  appsDomain: "*.iso-seg.127-0-0-1.nip.io"
  isolation_segments: ["isolated"]
  routing_table_sharding_mode: segments

udpForwarder:
  certificateSecret: "all-in-one-tls"

routingApi:
  enabled: false

tcpRouter:
  enabled: false