kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
featureGates:
  PodAndContainerStatsFromCRI: true
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    controllerManager:
      extraArgs:
        authorization-always-allow-paths: /healthz,/readyz,/livez,/metrics
        bind-address: 0.0.0.0
    scheduler:
      extraArgs:
        authorization-always-allow-paths: /healthz,/readyz,/livez,/metrics
        bind-address: 0.0.0.0
nodes:
- role: control-plane
- role: worker
  labels:
  extraPortMappings:
  - containerPort: 31080
    hostPort: 80
  - containerPort: 31443
    hostPort: 443
  - containerPort: 31222
    hostPort: 2222
  - containerPort: 32000
    hostPort: 32000
  - containerPort: 32001
    hostPort: 32001
  - containerPort: 32002
    hostPort: 32002
  - containerPort: 32003
    hostPort: 32003
  - containerPort: 32004
    hostPort: 32004
  - containerPort: 32005
    hostPort: 32005
  - containerPort: 32006
    hostPort: 32006
  - containerPort: 32007
    hostPort: 32007
  - containerPort: 32008
    hostPort: 32008
  - containerPort: 32009
    hostPort: 32009
  - containerPort: 32010
    hostPort: 32010
  - containerPort: 32011
    hostPort: 32011
  - containerPort: 32012
    hostPort: 32012
  - containerPort: 32013
    hostPort: 32013
  - containerPort: 32014
    hostPort: 32014
  - containerPort: 32015
    hostPort: 32015
  - containerPort: 32016
    hostPort: 32016
  - containerPort: 32017
    hostPort: 32017
  - containerPort: 32018
    hostPort: 32018
  - containerPort: 32019
    hostPort: 32019
- role: worker
  labels:
    cloudfoundry.org/cell: "true"
    cloudfoundry.org/zone: z1
