{{ if .Values.cloudController.enabled }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cc-uploader
  labels:
    app: cc-uploader
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/cc-uploader-config.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cc-uploader
  template:
    metadata:
      labels:
        app: cc-uploader
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/cc-uploader-config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: cc-uploader
          image: {{ .Values.ccUploader.image.repository }}:{{ default .Chart.AppVersion .Values.ccUploader.image.tag }}
          imagePullPolicy: {{ .Values.ccUploader.image.imagePullPolicy }}
          ports:
            - containerPort: 9091
          {{- if .Values.ccUploader.resources }}
          resources:
            {{- toYaml .Values.ccUploader.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: cc-uploader
              mountPath: /etc/ssl/certs/cc-uploader
            - name: cc-uploader-config
              mountPath: /cc-uploader
      {{- if .Values.ccUploader.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.ccUploader.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.ccUploader.tolerations }}
      tolerations:
        {{- toYaml .Values.ccUploader.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: cc-uploader
          secret:
            secretName: {{ required "ccUploader.certificateSecret is required" .Values.ccUploader.certificateSecret }}
        - name: cc-uploader-config
          configMap:
            name: cc-uploader-config
---
kind: Service
apiVersion: v1
metadata:
  name: cc-uploader
  labels:
    app: cc-uploader
spec:
  ports:
    - port: 9091
      targetPort: 9091
      name: tcp
      protocol: TCP
  selector:
    app: cc-uploader
{{ end }}
