{{ if .Values.tpsWatcher.enabled }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tps-watcher
  labels:
    app: tps-watcher
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/tps-watcher-config.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tps-watcher
  template:
    metadata:
      labels:
        app: tps-watcher
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/tps-watcher-config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: tps-watcher
          image: {{ .Values.tpsWatcher.image.repository }}:{{ default .Chart.AppVersion .Values.tpsWatcher.image.tag }}
          imagePullPolicy: {{ .Values.tpsWatcher.image.imagePullPolicy }}
          {{- if .Values.tpsWatcher.resources }}
          resources:
            {{- toYaml .Values.tpsWatcher.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tps-watcher
              mountPath: /etc/ssl/certs/tps-watcher
            - name: tps-watcher-config
              mountPath: /tps-watcher
            - name: tmp
              mountPath: /tmp
      {{- if .Values.tpsWatcher.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.tpsWatcher.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tpsWatcher.tolerations }}
      tolerations:
        {{- toYaml .Values.tpsWatcher.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: tps-watcher
          secret:
            secretName: {{ required "tpsWatcher.certificateSecret is required" .Values.tpsWatcher.certificateSecret }}
        - name: tps-watcher-config
          configMap:
            name: tps-watcher-config
{{- end }}
