---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: kind-settings
  namespace: {{ .Release.Namespace }}
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      cluster:
        name: outbound|443||gorouter.{{ .Release.Namespace }}.svc.cluster.local
      context: GATEWAY
    patch:
      operation: MERGE
      value:
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            use_downstream_protocol_config:
              http2_protocol_options:
                max_inbound_window_update_frames_per_data_frame_sent: 10000
  workloadSelector:
    labels:
      gateway.networking.k8s.io/gateway-name: istio-gateway
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: istio
  {{- with .Values.gateway.infrastructure }}
  infrastructure:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: All
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: all-in-one-tls
      mode: Terminate
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: ssh-proxy
    port: 2222
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-1
    port: 32000
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-2
    port: 32001
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-3
    port: 32002
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-4
    port: 32003
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-5
    port: 32004
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-6
    port: 32005
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-7
    port: 32006
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-8
    port: 32007
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-9
    port: 32008
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-10
    port: 32009
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-11
    port: 32010
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-12
    port: 32011
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-13
    port: 32012
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-14
    port: 32013
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-15
    port: 32014
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-16
    port: 32015
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-17
    port: 32016
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-18
    port: 32017
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-19
    port: 32018
    protocol: TCP
  - allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: TCPRoute
      namespaces:
        from: All
    name: tcp-route-20
    port: 32019
    protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: blobstore
spec:
  parentRefs:
    - name: istio-gateway
  hostnames:
    - blobstore.{{ .Values.systemDomain }}
    - "*.blobstore.{{ .Values.systemDomain }}"
  rules:
    - backendRefs:
        - name: minio
          port: 9000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wildcard-gorouter
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
    - name: istio-gateway
  hostnames:
  - "*.{{ .Values.appsDomain }}"
  - "*.{{ .Values.systemDomain }}"
  rules:
    - backendRefs:
        - name: gorouter
          port: 443
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: ssh-proxy
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: ssh-proxy
  rules:
    - backendRefs:
      - name: ssh-proxy
        port: 2222
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: gorouter-tls
spec:
  targetRefs:
    - kind: Service
      group: ""
      name: gorouter
  validation:
    hostname: gorouter
    caCertificateRefs:
      - kind: ConfigMap
        group: ""
        name: ca
{{- range $index := until 20 }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: cf-tcp-router-{{ add $index 1 }}
spec:
  parentRefs:
    - name: istio-gateway
      sectionName: tcp-route-{{ add $index 1 }}
  rules:
    - backendRefs:
      - name: cf-tcp-router
        port: {{ add 32000 $index }}
{{- end }}
