---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credhub
  labels:
    app: credhub
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/credhub-config.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credhub
  template:
    metadata:
      name: credhub
      labels:
        app: credhub
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/credhub-config.yaml") . | sha256sum }}
    spec:
      containers:
      - name: credhub-server
        image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        ports:
        - name: credhub-https
          containerPort: 8844
        - name: credhub-health
          containerPort: 9001
        env:
        - name: TRUST_STORE_PASSWORD
          value: changeit
        - name: KEY_STORE_PASSWORD
          value: changeit
        - name: ENCRYPTION_PASSWORD
          value: changeit
        - name: SERVER_CA_PRIVATE_KEY_PATH
          value: /etc/ssl/ca/tls.key
        - name: SERVER_CA_CERT_PATH
          value: /etc/ssl/ca/tls.crt
        - name: UAA_CA_PATH
          value: /etc/ssl/ca/tls.crt
        - name: UAA_URL
          value: https://uaa.{{ .Release.Namespace }}.svc.cluster.local:8443
        - name: SUBJECT_ALTERNATIVE_NAMES
          value: "DNS:{{ tpl .Values.hostname . }},DNS:credhub.{{ .Release.Namespace }}.svc.cluster.local,DNS:credhub.{{ .Release.Namespace }}.svc,DNS:credhub.{{ .Release.Namespace }},DNS:credhub"
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: ca
          mountPath: /etc/ssl/ca
        {{- if not .Values.db.skipSSLVerify }}
        - name: postgres-ca
          mountPath: /etc/ssl/certs/postgres
          readOnly: true
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        secret:
          secretName: credhub-config
      - name: ca
        secret:
          secretName: {{ required "caCertificateSecret is required" .Values.caCertificateSecret }}
      {{- if not .Values.db.skipSSLVerify }}
      - name: postgres-ca
        secret:
          secretName: {{ required "db.caCertificateSecret is required when db.skipSSLVerify is false" .Values.db.caCertificateSecret }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: credhub
  labels:
    app: credhub
spec:
  ports:
  - port: 8844
    name: credhub-https
    targetPort: 8844
    protocol: TCP
  - port: 9001
    name: credhub-health
    targetPort: 9001
    protocol: TCP
  selector:
    app: credhub
