---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credhub
  labels:
    app: credhub
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/credhub-configmap.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credhub
  template:
    metadata:
      name: credhub
      labels:
        app: credhub
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/credhub-configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: credhub-server
        image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        ports:
        - name: credhub-https
          containerPort: 8844
        - name: credhub-health
          containerPort: 9001
        env:
        - name: TRUST_STORE_PASSWORD
          value: changeit
        - name: TRUST_STORE_PATH
          value: /ssl/trust_store.jks
        volumeMounts:
        - name: config
          mountPath: /application.yml
          subPath: application.yml
        - name: ssl
          mountPath: /ssl
        - name: tmp
          mountPath: /tmp
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: credhub-config
      - name: tmp
        emptyDir: {}
      - name: ssl
        secret:
          secretName: {{ required "certificateSecret is required" .Values.certificateSecret }}
---
apiVersion: v1
kind: Service
metadata:
  name: credhub
  labels:
    app: credhub
spec:
  ports:
  - port: 8844
    name: credhub-https
    targetPort: 8844
    protocol: TCP
  - port: 9001
    name: credhub-health
    targetPort: 9001
    protocol: TCP
  selector:
    app: credhub
---
kind: TLSRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: credhub
  namespace: default
spec:
  parentRefs:
    - name: istio-gateway
  hostnames:
  - "{{ .Values.hostname }}"
  rules:
  - backendRefs:
    - name: credhub
      port: 8844
