apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - all.yaml
patchesStrategicMerge:
  - patch-cloud-controller-telegraf.yaml
  - patch-cc-worker-telegraf.yaml
  - patch-scheduler-telegraf.yaml
configMapGenerator:
  - name: telegraf-config
    files:
      - capi.telegraf.conf
      - worker.telegraf.conf
      - scheduler.telegraf.conf