apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-controller
spec:
  template:
    spec:
      containers:
        - name: telegraf
          image: telegraf:1.39.2
          resources: {}
          volumeMounts:
            - name: telegraf-config
              mountPath: /etc/telegraf
            - name: var-run
              mountPath: /var/run
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
