[[processors.override]]
  name_prefix = "scheduler."

[[inputs.prometheus]]
  urls = ["unix:///var/run/cloud_controller_metrics.sock?path=/internal/v4/metrics"]

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"