apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: public-networks
spec:
  endpointSelector:
    matchExpressions:
      - key: cloudfoundry.org/app-guid
        operator: Exists
  egress:
    - toCIDRSet:
      - cidr: 0.0.0.0/0
        except:
          - 10.0.0.0/8
          - 169.254.0.0/16
          - 172.16.0.0/12
          - 192.168.0.0/16
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: default
            service.istio.io/canonical-name: istio-gateway-istio
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "80"
              protocol: TCP