certificateSecret: ""
hostname: "uaa.127-0-0-1.nip.io"
address: "https://uaa.127-0-0-1.nip.io"
loginAddress: "https://login.127-0-0-1.nip.io"

image:
  repository: ghcr.io/cloudfoundry/k8s/uaa
  tag: ""
  imagePullPolicy: IfNotPresent

nodeSelector: ~
tolerations: ~

uaaAdminSecret: ~
ccAdminPassword: ~
oauthClientsSecret: ~
uaadb:
  name: uaa
  password: ~
  user: postgres
  port: 5432
  address: postgresql.default.svc.cluster.local

uaaConfigOverrides: {}
