hostname: "credhub.default.svc.cluster.local"
uaa:
  address: "https://uaa.default.svc.cluster.local:8443"

image:
  repository: ghcr.io/cloudfoundry/k8s/credhub
  tag: ""
  imagePullPolicy: IfNotPresent

nodeSelector: ~
tolerations: ~

caCertificateSecret: ""

db:
  name: credhub
  password: ~
  user: postgres
  port: 5432
  address: postgresql.default.svc.cluster.local
  caCertificateSecret: ""
  skipSSLVerify: true
