{{- if .Values.locket.enabled }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: locket
  labels:
    app: locket
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/locket-config.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locket
  template:
    metadata:
      labels:
        app: locket
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/locket-config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: locket
          image: {{ .Values.locket.image.repository }}:{{ default .Chart.AppVersion .Values.locket.image.tag }}
          imagePullPolicy: {{ .Values.locket.image.imagePullPolicy }}
          ports:
            - containerPort: 8891
          {{- if .Values.locket.resources }}
          resources:
            {{- toYaml .Values.locket.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: locket
              mountPath: /etc/ssl/certs/locket
            {{- if not .Values.locketdb.skipSSLVerify }}
            - name: postgres-tls
              mountPath: /etc/ssl/certs/postgres
              readOnly: true
            {{- end }}
            - name: locket-config
              mountPath: /locket
      {{- if .Values.locket.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.locket.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.locket.tolerations }}
      tolerations:
        {{- toYaml .Values.locket.tolerations | nindent 8 }}
      {{- end }}
      volumes:
        - name: locket
          secret:
            secretName: {{ required "locket.certificateSecret is required" .Values.locket.certificateSecret }}
        {{- if not .Values.locketdb.skipSSLVerify }}
        - name: postgres-tls
          secret:
            secretName: {{ required "locketdb.caCertificateSecret is required when locketdb.skipSSLVerify is false" .Values.locketdb.caCertificateSecret }}
        {{- end }}
        - name: locket-config
          secret:
            secretName: locket-config
---
kind: Service
apiVersion: v1
metadata:
  name: locket
  labels:
    app: locket
spec:
  ports:
    - port: 8891
      targetPort: 8891
      protocol: TCP
  selector:
    app: locket
{{- end }}
