ccDeploymentUpdater:
  resources: ~
  nodeSelector: ~
  tolerations: ~

ccWorker:
  resources: ~
  nodeSelector: ~
  tolerations: ~

ccUploader:
  resources: ~
  certificateSecret: ""
  hostname: "cc-uploader.default.svc.cluster.local"
  image:
    repository: ghcr.io/cloudfoundry/k8s/cc-uploader
    tag: ""
    imagePullPolicy: IfNotPresent
  nodeSelector: ~
  tolerations: ~

ccWorkerClock:
  resources: ~
  nodeSelector: ~
  tolerations: ~

cloudController:
  enabled: false
  resources: ~
  certificateSecret: ""
  appDomain: apps.127-0-0-1.nip.io
  externalDomain: api.127-0-0-1.nip.io
  internalDomain: cloud-controller.default.svc.cluster.local
  internalServiceHostname: cloud-controller.default.svc.cluster.local
  systemDomain: system.127-0-0-1.nip.io
  appSSHEndpoint: ssh.127-0-0-1.nip.io:2222
  sshProxyKeyFingerprint: ""
  loginUrl: https://login.127-0-0-1.nip.io
  image:
    repository: ghcr.io/cloudfoundry/k8s/cloud-controller
    tag: ""
    imagePullPolicy: IfNotPresent
  doppler:
    url: wss://doppler.127-0-0-1.nip.io:443
  logCache:
    url: https://log-cache.127-0-0-1.nip.io
  logStream:
    url: https://log-stream.127-0-0-1.nip.io
  uaa:
    url: https://uaa.127-0-0-1.nip.io
  blobstore:
    type: storage-cli
    resource_directory_key: cc-resources
    app_package_directory_key: cc-packages
    droplet_directory_key: cc-droplets
    buildpack_directory_key: cc-buildpacks
    storage_cli:
      host: http://blobstore.127-0-0-1.nip.io
      aws_access_key_id: admin
      aws_secret_access_key: ~
    fog_connection:
      provider: ~
  diego:
    fileServerUrl: https://fileserver.127-0-0-1.nip.io
    ccUploaderUrl: https://cc-uploader.default.svc.cluster.local:9091
  credhubApi:
    internalUrl: https://credhub.default.svc.cluster.local:8844
    externalUrl: ""
  nats:
    address: nats.default.svc.cluster.local:4222
  nodeSelector: ~
  tolerations: ~
  enableCommaDelimitedDestinations: false

localWorker:
  image:
    repository: ghcr.io/cloudfoundry/k8s/cloud-controller
    tag: ""
    imagePullPolicy: IfNotPresent
  resources: ~

routeRegistrar:
  image:
    repository: ghcr.io/cloudfoundry/k8s/route-registrar
    # sync: release=routing
    tag: "0.375.0"
    imagePullPolicy: IfNotPresent
  resources: ~

nginx:
  image:
    repository: ghcr.io/cloudfoundry/k8s/cc-nginx
    tag: ""
    imagePullPolicy: IfNotPresent
  resources: ~

udpForwarder:
  image:
    repository: ghcr.io/cloudfoundry/k8s/udp-forwarder
    # sync: release=loggregator-agent
    tag: "8.3.17"
    imagePullPolicy: IfNotPresent
  resources: ~
  certificateSecret: ""

tpsWatcher:
  enabled: false
  resources: ~
  certificateSecret: ""
  hostname: tps.default.svc.cluster.local
  image:
    repository: ghcr.io/cloudfoundry/k8s/tps-watcher
    tag: ""
    imagePullPolicy: IfNotPresent
  nodeSelector: ~
  tolerations: ~

ccdb:
  name: cc
  password: ~
  user: postgres
  port: 5432
  address: postgresql.default.svc.cluster.local


oauthClientsSecret: ~
