services:
  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs-server
    restart: always
    privileged: true
    networks:
      - kind
    environment:
      SHARED_DIRECTORY: /exports
    volumes:
      - nfs-exports:/exports

volumes:
  nfs-exports:

networks:
  kind:
    external: true
