gorouter:
  enabled: false
  certificateSecret: ""
  name: gorouter
  hostname: "gorouter.127-0-0-1.nip.io"
  appsDomain: "*.apps.127-0-0-1.nip.io"
  isolationSegments: []
  routingTableShardingMode: all
  image:
    repository: ghcr.io/cloudfoundry/k8s/gorouter
    tag: ""
    imagePullPolicy: IfNotPresent
  nodeSelector: ~
  tolerations: ~

udpForwarder:
  certificateSecret: ""
  image:
    repository: ghcr.io/cloudfoundry/k8s/udp-forwarder
    # sync: release=loggregator-agent
    tag: "8.3.17"
    imagePullPolicy: IfNotPresent

routingApi:
  enabled: false
  certificateSecret: ""
  locketCertificateSecret: ""
  loggregatorCertificateSecret: ""
  uaaCertificateSecret: ""
  systemDomain: "127-0-0-1.nip.io"
  sqldb:
    name: routing_api
    password: ~
    user: postgres
    port: 5432
    address: postgresql.{{ .Release.Namespace }}.svc.cluster.local
    caCertificateSecret: ""
    skipSSLVerify: true
  locketAddress: locket.{{ .Release.Namespace }}.svc.cluster.local:8891
  uaa:
    address: uaa.{{ .Release.Namespace }}.svc.cluster.local
    port: 8443
  image:
    repository: ghcr.io/cloudfoundry/k8s/routing-api
    tag: ""
    imagePullPolicy: IfNotPresent
  nodeSelector: ~
  tolerations: ~

tcpRouter:
  enabled: false
  certificateSecret: ""
  oauthClientsSecret: ""
  image:
    repository: ghcr.io/cloudfoundry/k8s/cf-tcp-router
    tag: ""
    imagePullPolicy: IfNotPresent
  haproxy:
    image:
      repository: haproxy
      tag: "3.3.3-alpine"
      imagePullPolicy: IfNotPresent
    resources: ~
  uaa:
    address: uaa.{{ .Release.Namespace }}.svc.cluster.local
    port: 8443
  routingApi:
    address: https://routing-api.{{ .Release.Namespace }}.svc.cluster.local
    port: 3001
  nodeSelector: ~
  tolerations: ~
  isolationSegments: []

routeRegistrar:
  image:
    repository: ghcr.io/cloudfoundry/k8s/route-registrar
    # sync: release=routing
    tag: "0.375.0"
    imagePullPolicy: IfNotPresent
