name: Setup CF Tests
description: Common setup for CF testing workflows

inputs:
  test-org:
    description: 'CF test repository organization name (e.g., cloudfoundry, sap-contributions)'
    required: false
    default: 'cloudfoundry'
  test-repo:
    description: 'CF test repository name (e.g., cf-acceptance-tests, cf-smoke-tests)'
    required: true
  test-branch:
    description: 'CF test repository branch to checkout'
    required: false
    default: 'develop'
  config-template:
    description: 'Config template file path'
    required: true
  config-output:
    description: 'Config output file path'
    required: true

outputs:
  test-repo-path:
    description: 'Path to the checked out test repository'
    value: ${{ inputs.test-repo }}

runs:
  using: "composite"
  steps:
    - name: checkout CF test repository
      uses: actions/checkout@v6
      with:
        repository: "${{ inputs.test-org }}/${{ inputs.test-repo }}"
        ref: ${{ inputs.test-branch }}
        github-server-url: https://github.com
        path: "${{ inputs.test-repo }}"
    - name: setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: ./${{ inputs.test-repo }}/go.mod
        cache: false
    - name: setup Python
      uses: actions/setup-python@v6
      with:
        python-version: "3"
    - name: templating config
      shell: bash
      run: |
        source temp/secrets.sh
        python3 -c 'import os,sys;[sys.stdout.write(os.path.expandvars(l)) for l in sys.stdin]' < ${{ inputs.config-template }} > ${{ inputs.config-output }}
