name: CF Smoke Tests on KinD
run-name: >-
  CF Smoke Tests on KinD${{ github.event_name == 'schedule' && ' (scheduled)' || github.event_name == 'workflow_dispatch' && github.event.inputs.fresh-validation == 'true' && ' (fresh validation)' || '' }}

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      minimal:
        description: 'Run minimal installation (skip optional components)'
        type: boolean
        required: false
        default: true
      fresh-validation:
        description: 'Use versions of cf-deployment from the develop branch'
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 7 * * 1'

jobs:
  kind-smoke:
    uses: ./.github/workflows/smoke-run.yaml
    permissions:
      id-token: write
      contents: read
    with:
      container-runtime: docker
      install-optional-components: ${{ github.event_name == 'pull_request' && 'false' || inputs.minimal != true && 'true' || 'false' }}
      artifact-name: report.json

  kind-smoke-podman:
    uses: ./.github/workflows/smoke-run.yaml
    permissions:
      id-token: write
      contents: read
    with:
      container-runtime: podman
      install-optional-components: ${{ github.event_name == 'pull_request' && 'false' || inputs.minimal != true && 'true' || 'false' }}
      artifact-name: report-podman.json
